name: HAC_env
channels:
  - pyg
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.10
  - pip=22.3.1
  - pytorch=1.12.1
  - torchvision=0.13.1
  - pytorch-scatter
  - tqdm
  - mkl=2022.1
  - pip:
    - einops
    - wandb
    - lpips
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/gridencoder
    - submodules/arithmetic
